package com.steptrackerpro

import com.facebook.react.bridge.ReactApplicationContext

/**
 * New architecture shim. `NativeStepTrackerProSpec` is generated by codegen
 * from `src/NativeStepTrackerPro.ts` at build time.
 */
abstract class StepTrackerProSpec internal constructor(context: ReactApplicationContext) :
    NativeStepTrackerProSpec(context)
