package com.steptrackerpro.core

import org.json.JSONArray
import org.json.JSONObject

/**
 * Something that happened to the device or the tracker that a server judging
 * a day wants to see next to the numbers: the clock moved, the phone
 * rebooted, today was reset, a charger went in mid-walk. Logged only while
 * `fraudDetection.enabled`.
 */
data class IntegrityEvent(
    /** Epoch ms. */
    val at: Long,
    val type: String,
    val detail: Map<String, Any?> = emptyMap()
) {
    fun toMap(): Map<String, Any?> = mapOf("at" to at, "type" to type, "detail" to detail)

    companion object {
        /** The wall clock was set; `detail.jumpMs` is how far, from the boot id's move. */
        const val CLOCK_CHANGED = "clock_changed"
        const val TIMEZONE_CHANGED = "timezone_changed"
        const val REBOOT = "reboot"
        const val RESET_TODAY = "reset_today"
        const val HISTORY_CLEARED = "history_cleared"
        /** `detail.keys` lists the integrity-relevant config keys that changed. */
        const val CONFIG_CHANGED = "config_changed"
        /** The service moved to a different step sensor; `detail.from` and `detail.to`. */
        const val SENSOR_CHANGED = "sensor_changed"
        const val CHARGING_STARTED = "charging_started"
        const val CHARGING_STOPPED = "charging_stopped"
        /** Activity Recognition reported a new state; `detail.activity`. */
        const val ACTIVITY_CHANGED = "activity_changed"
        /** Something other than the user restarted the service; `detail.reason`. */
        const val SERVICE_RECOVERED = "service_recovered"
        /** A signed snapshot's key was (re)generated by `attestDevice()`. */
        const val DEVICE_ATTESTED = "device_attested"
    }
}

/** org.json to plain Kotlin collections and back, for the small JSON columns. */
object JsonMaps {

    fun toJson(map: Map<String, Any?>): String = wrap(map).toString()

    fun parse(text: String?): Map<String, Any?> {
        if (text.isNullOrEmpty()) return emptyMap()
        return runCatching { toMap(JSONObject(text)) }.getOrDefault(emptyMap())
    }

    fun toMap(obj: JSONObject): Map<String, Any?> {
        val out = LinkedHashMap<String, Any?>()
        obj.keys().forEach { key -> out[key] = unwrap(obj.opt(key)) }
        return out
    }

    private fun unwrap(value: Any?): Any? = when (value) {
        null, JSONObject.NULL -> null
        is JSONObject -> toMap(value)
        is JSONArray -> (0 until value.length()).map { unwrap(value.opt(it)) }
        else -> value
    }

    private fun wrap(value: Any?): Any = when (value) {
        null -> JSONObject.NULL
        is Map<*, *> -> JSONObject().also { obj ->
            value.forEach { (k, v) -> obj.put(k.toString(), wrap(v)) }
        }
        is Iterable<*> -> JSONArray().also { arr -> value.forEach { arr.put(wrap(it)) } }
        is Array<*> -> JSONArray().also { arr -> value.forEach { arr.put(wrap(it)) } }
        // org.json refuses NaN and infinity outright; a signed snapshot must
        // not fail because one derived figure had nothing to divide by.
        is Double -> if (value.isFinite()) value else JSONObject.NULL
        is Float -> if (value.isFinite()) value.toDouble() else JSONObject.NULL
        else -> value
    }
}
