export {
  StepTracker,
  StepTracker as default,
  estimateStride,
  isSupported,
} from './StepTracker';
export { StepTrackerError } from './errors';
export type { StepTrackerErrorCode } from './errors';
export {
  DEFAULT_CONFIG,
  HEALTH_CONNECT_MAX_PROMPTS,
  HEALTH_CONNECT_PACKAGE,
  STRIDE_COEFFICIENT,
} from './constants';
export * from './hooks';
export type {
  AnyHealthConnectRecord,
  BackgroundRestrictionStatus,
  CompanionApp,
  CurrentStepSource,
  DayChangedEvent,
  DayRecord,
  DeviceAttestation,
  DeviceCapabilities,
  DeviceIntegritySignals,
  EventSubscription,
  FraudDetectionConfig,
  GapRecovery,
  GoalProgressEvent,
  GoalReachedEvent,
  HealthConnectAvailability,
  HealthConnectChanges,
  HealthConnectDistanceRecord,
  HealthConnectReadType,
  HealthConnectRecord,
  HealthConnectRecordBase,
  HealthConnectRecordList,
  HealthConnectRecordOptions,
  HealthConnectRecordType,
  HealthConnectStatus,
  HealthConnectStatusEvent,
  HealthConnectStepRecord,
  HistoryBackfilledEvent,
  IntegrityErrorDetails,
  IntegrityEvent,
  IntegrityEventType,
  IntegrityFlag,
  IntegrityFlagType,
  IntegrityMode,
  IntegrityReport,
  IntegrityToken,
  IntegrityTokenOptions,
  MotionSamplingConfig,
  MotionWindow,
  PermissionStatus,
  RangeOptions,
  RangeStats,
  RecordingMethodBreakdown,
  RemoteSyncFailure,
  RemoteSyncStatus,
  RequestHealthConnectOptions,
  ResolvedStepSource,
  SensorSource,
  Sex,
  SnapshotHealthConnectRecords,
  SnapshotSignature,
  StepMinute,
  StepSnapshot,
  StepSource,
  StepSourceChangedEvent,
  StepSourceKind,
  StepSourceList,
  StepSourcePolicy,
  StepTrackerConfig,
  StepTrackerEvent,
  StepTrackerEventMap,
  StepsChangedEvent,
  SuspiciousActivityEvent,
  SyncAuthFailedEvent,
  SyncEvent,
  SyncStatus,
  TrackingHealth,
  TrackingState,
  TrackingStateEvent,
  VerificationSnapshot,
  VerificationSnapshotOptions,
  VerificationSnapshotPart,
  WearableTrust,
} from './types';
